### ISSUE TITLE
403 forbidden for url

### ISSUE THREAD

**Issue by ddeath** [thisbejim/Pyrebase#105] opened 2016-11-15 13:51 UTC
Hi there,

I am getting some strange exception very occasionally. Any idea why?

    Exception in thread Thread-2:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.5/threading.py", line 862, in run
        self._target(*self._args, **self._kwargs)
      File "/xxxxxx/lib/python3.5/site-packages/sseclient/sseclient.py", line 67, in connect
        self._connect()
      File "/xxxxxx/lib/python3.5/site-packages/pyrebase/pyrebase.py", line 520, in _connect
        super(ClosableSSEClient, self)._connect()
      File "/xxxxxx/lib/python3.5/site-packages/sseclient/sseclient.py", line 54, in _connect
        self.resp.raise_for_status()
      File "/xxxxxx/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s-usc1c-nss-120.firebaseio.com/status/state.json?ns=xxxxxxx&sse=true

I am on 3.0.24 pyrebase using stream with service account

**Comment by thisbejim** [comment] 2016-11-15 22:27
Hi @ddeath, how long into streaming are you getting this error?

**Comment by ddeath** [comment] 2016-11-16 14:00
@thisbejim it is variable.... I just got that exception after 3-4 hours it does not crash program, just that thread and it looks like next streaming events are received.

**Comment by thisbejim** [comment] 2016-11-16 22:48
I think I see the issue, in https://github.com/thisbejim/Pyrebase/commit/fad1ab754daa4c5239f2c805f4919f968c9cb265 I added the fix for stale service account tokens when streaming which restarts streams with new auth tokens. It might be that I'm not closing the previous stream threads properly, will take a look! Cheers for opening this issue 👍

**Comment by thisbejim** [comment] 2016-11-16 23:04
Nope I was wrong, I don't create a new thread for each new stream there is only one so not sure again.

**Comment by thisbejim** [comment] 2016-11-17 02:19
I was able to replicate the issue and it looks like although we open a new stream every half hour we aren't properly closing the previous one. So the previous streaming connection stays open passed when the service account tokens are valid and so eventually that stream is unauthorised.

This does not have an effect on the expected results of the current stream in any way but it would still be good to clean up the closing of streams. I've added a potential fix and am running a test atm to see if it resolves the problem.

**Comment by thisbejim** [comment] 2016-11-17 10:21
I was unsuccessful in solving this issue for now but the main take away is that this does not cause any problems for the actual streaming functionality.

**Comment by ddeath** [comment] 2016-11-17 10:31
I agree, that it looks it does not cause any problem, only that it print exception to console.

**Comment by busla** [comment] 2016-11-23 06:37
I can reproduce this as well with no effect on streaming and it refreshes my token 4 seconds later.

```python
[Thread-3:401 -        _make_request() ] - 2016-11-22 20:09:48,010:  "GET /test/ruv.json?ns=streampimp&sse=true HTTP/1.1" 403 37
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/levy/Code/streampimp/venv/lib/python3.5/site-packages/sseclient/sseclient.py", line 68, in connect
    self._connect()
  File "/Users/levy/Code/streampimp/venv/lib/python3.5/site-packages/pyrebase/pyrebase.py", line 520, in _connect
    super(ClosableSSEClient, self)._connect()
  File "/Users/levy/Code/streampimp/venv/lib/python3.5/site-packages/sseclient/sseclient.py", line 55, in _connect
    self.resp.raise_for_status()
  File "/Users/levy/Code/streampimp/venv/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s-usc1c-nss-118.firebaseio.com/test/ruv.json?ns=streampimp&sse=true

[Thread-2:664 - access_token_expired() ] - 2016-11-22 20:09:52,667:  access_token is expired. Now: 2016-11-22 20:09:52.667505, token_expiry: 2016-11-22 20:09:45.608371
[Thread-2:100 -      make_signed_jwt() ] - 2016-11-22 20:09:52,683:  [b'my-token']
[Thread-2:795 -  _do_refresh_request() ] - 2016-11-22 20:09:52,683:  Refreshing access_token
```

**Comment by andreask1** [comment] 2016-11-27 11:17
@thisbejim Is automatic token refresh for streaming also available when using authentication with email and password (and not only with service accounts)?

I'm using Firebase in an IoT setup and want to have granular access control instead of having to give away the service account credentials to every device. Basically I want to give every device separate user/pass credentials and let them run for months, streaming continuously from Firebase (handling token expiration and network errors reliably).

**Closed** 2016-12-12 23:47 UTC
