### ISSUE TITLE
Stream Breaks

### ISSUE THREAD

**Issue by diegocerdan** [thisbejim/Pyrebase#72] opened 2016-09-28 14:34 UTC
When I have a stream open for hours at some point it breaks and stops receiving messages.

Is this a common issue? 

Is there a way of checking the health of a stream?

Should I reopen the stream periodically?

**Comment by thisbejim** [comment] 2016-10-03 03:47
Thanks for raising this issue @diegocerdan, I am looking into this at the moment,

**Comment by thisbejim** [comment] 2016-10-03 05:00
Hi @diegocerdan, how were you streaming? Were you using a user token, like this:

```
my_stream = db.child("test").stream(stream_handler, user['idToken'])
```

**Comment by diegocerdan** [comment] 2016-10-03 07:14
I'm streaming like this:

`my_stream = database.child('messages').child('queue').stream(stream_handler)`


I'm not using tokens right now but my rules are full open read & write:
```
{
  "rules": {
    ".read": true,
    ".write": true
  }
}
```

**Comment by thisbejim** [comment] 2016-10-03 07:15
Thanks @diegocerdan, that info is a big help!

**Comment by thisbejim** [comment] 2016-10-03 07:17
Oh one more thing - does your firebase config use a service account?

**Comment by diegocerdan** [comment] 2016-10-03 07:26
Yes, I'm using a service account.

**Comment by thisbejim** [comment] 2016-10-03 07:27
Cheers!

**Comment by thisbejim** [comment] 2016-10-04 01:32
So here is what is happening: 

When using a service account config all requests are authenticated as an admin by default, including streaming. When making standard requests like get() we refresh the service account auth token before each request which ensures that we don't use stale tokens (tokens only last 1 hour). 

However, when we make a streaming request it is a single request that lasts as long as we are running the stream, and if we stream for over an hour the auth token becomes stale and Firebase sends us an event telling us about it instead of the sending us the data we are looking for. This happens even if our security rules for read and right are set to "true".

To resolve this we will have to figure out how to apply fresh auth tokens to our stream session without closing the stream itself.

**Comment by diegocerdan** [comment] 2016-10-04 08:29
Not using a service account would also solve the issue?

**Comment by thisbejim** [comment] 2016-10-04 09:17
Yeah I think so (haven't tested) if it doesn't break anything else you are doing.

**Comment by bkawk** [comment] 2016-10-12 01:20
We have tried with and without a service account. We are sending the token to start the stream, all works well initially then just as described above the stream magically stops at some point in the future. 
We then made a timer with logging as seen below. The logs get written and never stop but the stream never restarts once it fails.

`
# log the steam
def makeLog(msg): 
    db.child("email/logs").push({"status":msg, "time": int(time.time())})
    logging.info(msg)

# watch the queue and restart every 45min
def startStream (): 
    makeLog('Starting')
    threading.Timer(int(2700, startStream).start ()
    makeLog('Starting Stream')
    my_stream = db.child("email/queue/").stream(stream_handler, token)
    makeLog('Closing Stream')
    my_stream.close()
    makeLog('Starting Stream')
    my_stream = db.child("email/queue/").stream(stream_handler, token)
startStream()`

**Comment by thisbejim** [comment] 2016-10-12 02:43
Thank you for the info @bkawk, I did a bit of asking around and it does look like stopping and starting the stream is the way to go (you can't replace the auth token in the header). 

I've recently added the source code of SSEClient, the library we use to handle streaming, directly to Pyrebase so that we can modify it to stop and restart streams automatically. When I get the time I will add that in but no ETA at the moment.

**Comment by bkawk** [comment] 2016-10-12 04:14
@thisbejim The stopping and starting of the stream is not solving the problem

**Comment by thisbejim** [comment] 2016-10-12 04:22
Yep so how it will work internally is that we will have a getter function that we pass to SSEClient and when we stop the stream we will fetch the new credentials to apply to a new stream.

**Comment by thisbejim** [comment] 2016-10-12 04:24
But yes the problem is that the tokens are stale after 1 hour.

**Comment by thisbejim** [comment] 2016-11-06 06:58
Streaming with service accounts is now fixed with https://github.com/thisbejim/Pyrebase/commit/fad1ab754daa4c5239f2c805f4919f968c9cb265

**Closed by thisbejim** 2016-11-06 06:58 UTC

**Comment by ddeath** [comment] 2016-11-14 23:02
hi, this is probably relevant, because stream is working fine after starting, but then it fails:

    Exception in thread Thread-2:
    Traceback (most recent call last):
      File "/xxxxxxx/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 393, in _make_request
        six.raise_from(e, None)
      File "<string>", line 2, in raise_from
      File "/xxxxxxx/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
        httplib_response = conn.getresponse()
      File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
        response.begin()
      File "/usr/lib/python3.5/http/client.py", line 297, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
        line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
      File "/usr/lib/python3.5/socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "/usr/lib/python3.5/ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "/usr/lib/python3.5/ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    TimeoutError: [Errno 110] Connection timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/xxxxxxx/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/xxxxxxx/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/xxxxxxx/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 261, in increment
        raise six.reraise(type(error), error, _stacktrace)
      File "/xxxxxxx/lib/python3.5/site-packages/requests/packages/urllib3/packages/six.py", line 686, in reraise
        raise value
      File "/xxxxxxx/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "/xxxxxxx/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 395, in _make_request
        self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
      File "/xxxxxxx/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 326, in _raise_timeout
        raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='zzzzzz.firebaseio.com', port=443): Read timed out. (read timeout=None)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.5/threading.py", line 862, in run
        self._target(*self._args, **self._kwargs)
      File "/xxxxxxx/lib/python3.5/site-packages/sseclient/sseclient.py", line 67, in connect
        self._connect()
      File "/xxxxxxx/lib/python3.5/site-packages/pyrebase/pyrebase.py", line 520, in _connect
        super(ClosableSSEClient, self)._connect()
      File "/xxxxxxx/lib/python3.5/site-packages/sseclient/sseclient.py", line 48, in _connect
        self.resp = self.requester.get(self.url, stream=True, **self.requests_kwargs)
      File "/xxxxxxx/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/xxxxxxx/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/xxxxxxx/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/xxxxxxx/lib/python3.5/site-packages/requests/adapters.py", line 499, in send
        raise ReadTimeout(e, request=request)
    requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='zzzzzz.firebaseio.com', port=443): Read timed out. (read timeout=None)

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "/usr/lib/python3.5/threading.py", line 862, in run
        self._target(*self._args, **self._kwargs)
      File "/xxxxxxx/lib/python3.5/site-packages/pyrebase/pyrebase.py", line 556, in start_stream
        msg_data = json.loads(msg.data)
      File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


I am running it with service account in fbase config and then:

    self.fBaseDB.child("status").child('state').stream(self._handle_betting_status_change)

version of pyrebase is 3.0.24

Any suggestions?
